### ISSUE TITLE
Images need to be cropped (circular if poss.)

### ISSUE THREAD

**Issue by hugomd** [wiredmonash/wiredmonash.github.io#2]
<img width="1208" alt="screen shot 2016-03-28 at 3 05 01 pm" src="https://cloud.githubusercontent.com/assets/1646536/14070763/75ce03e0-f4f6-11e5-8085-88089553d9ed.png">

**Comment by josh-** [comment]
Cropping fixed, should we also follow [UNIHACK](http://unihack.net/about) round avatars?
