### ISSUE TITLE
Nitpicking

### ISSUE THREAD

**Issue by hugomd** [wiredmonash/wiredmonash.github.io#3]
This needs to be 2015-2016.
<img width="243" alt="screen shot 2016-03-28 at 3 05 41 pm" src="https://cloud.githubusercontent.com/assets/1646536/14070779/a05f32a0-f4f6-11e5-9dba-322092835cf7.png">

**Comment by josh-** [comment]
@hugomd it says so already?

**Comment by hugomd** [comment]
@josh- Nicht so!
